# Generated by Django 2.2.1 on 2020-02-18 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileUser',
            fields=[
                ('userid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=80)),
                ('cod_fis', models.CharField(max_length=16)),
                ('vip', models.BooleanField(default=False)),
                ('org_unit', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SimProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iccid', models.CharField(max_length=20)),
                ('pin', models.CharField(max_length=5)),
                ('puk', models.CharField(max_length=11)),
                ('usage', models.CharField(choices=[('P', 'Telephony'), ('I', 'Internet Key'), ('W', 'Twin Card'), ('R', 'Router'), ('T', 'Tablet'), ('H', 'Hybrid'), ('O', 'Other')], max_length=1)),
                ('sim_type', models.CharField(choices=[('D', 'DATI'), ('V', 'VOCE')], max_length=1)),
                ('active', models.BooleanField(default=False)),
                ('invisible', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile.SimProfile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile.MobileUser')),
            ],
        ),
    ]
