# Generated by Django 2.2.1 on 2020-02-20 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=16, unique=True)),
                ('serial_no', models.CharField(max_length=30)),
                ('notes', models.TextField()),
                ('date_purchased', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MobileDeviceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('variant', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MobileDeviceOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MobileDeviceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='sim',
            name='sim_type',
            field=models.CharField(choices=[('D', 'DATA'), ('V', 'VOICE')], max_length=1),
        ),
        migrations.CreateModel(
            name='MobileDeviceAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_stop', models.DateField()),
                ('docs_status', models.CharField(choices=[('S', 'Sent'), ('R', 'Received'), ('C', 'Completed'), ('U', 'Unknown')], max_length=1)),
                ('mode', models.CharField(choices=[('T', 'Temporary'), ('P', 'Permanent')], max_length=1)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.MobileDevice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.MobileUser')),
            ],
        ),
        migrations.AddField(
            model_name='mobiledevice',
            name='assignment',
            field=models.ManyToManyField(through='mobile.MobileDeviceAssignment', to='mobile.MobileUser'),
        ),
        migrations.AddField(
            model_name='mobiledevice',
            name='installed_sim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile.Sim'),
        ),
        migrations.AddField(
            model_name='mobiledevice',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.MobileDeviceModel'),
        ),
        migrations.AddField(
            model_name='mobiledevice',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.MobileDeviceOwner'),
        ),
        migrations.AddField(
            model_name='mobiledevice',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile.MobileDeviceStatus'),
        ),
    ]
