# Generated by Django 2.2.10 on 2020-02-21 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_auto_20200220_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiledevice',
            name='date_purchased',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobiledevice',
            name='installed_sim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile.Sim'),
        ),
        migrations.AlterField(
            model_name='mobiledevice',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobiledevice',
            name='serial_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mobiledevice',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile.MobileDeviceStatus'),
        ),
        migrations.AlterField(
            model_name='mobiledeviceassignment',
            name='date_stop',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobiledeviceassignment',
            name='docs_status',
            field=models.CharField(choices=[('S', 'Sent'), ('R', 'Received'), ('C', 'Completed'), ('U', 'Unknown')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='mobiledeviceassignment',
            name='mode',
            field=models.CharField(choices=[('T', 'Temporary'), ('P', 'Permanent')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='mobiledevicemodel',
            name='variant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mobiledevicestatus',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mobileuser',
            name='cod_fis',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='mobileuser',
            name='email',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='mobileuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mobileuser',
            name='org_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sim',
            name='sim_type',
            field=models.CharField(choices=[('D', 'DATA'), ('V', 'VOICE')], default='V', max_length=1),
        ),
        migrations.AlterField(
            model_name='sim',
            name='usage',
            field=models.CharField(choices=[('P', 'Telephony'), ('I', 'Internet Key'), ('W', 'Twin Card'), ('R', 'Router'), ('T', 'Tablet'), ('H', 'Hybrid'), ('O', 'Other')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='sim',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile.MobileUser'),
        ),
        migrations.AlterField(
            model_name='simprofile',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
