# Generated by Django 2.2.1 on 2020-03-02 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_auto_20200221_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MobilePhoneNumber',
            fields=[
                ('number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('ok_to_show', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile.MobileOwner')),
            ],
        ),
        migrations.AddField(
            model_name='sim',
            name='imsi',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='sim',
            name='sim_format',
            field=models.CharField(choices=[('F', 'Full-size'), ('M', 'Mini-SIM'), ('U', 'Micro-SIM'), ('N', 'Nano-SIM'), ('E', 'eSIM')], default='N', max_length=1),
        ),
        migrations.CreateModel(
            name='MobilePhoneNumberEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event', models.CharField(choices=[('A', 'Activation'), ('C', 'Cessation'), ('T', 'Takeover'), ('K', 'Ok to takeover'), ('X', 'SIM change'), ('U', 'Transfer to other user'), ('O', 'Other')], max_length=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.MobilePhoneNumber')),
            ],
        ),
        migrations.AddField(
            model_name='mobilephonenumber',
            name='sim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile.Sim'),
        ),
        migrations.AddField(
            model_name='mobilephonenumber',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile.MobileUser'),
        ),
    ]
