# Generated by Django 2.2.1 on 2020-03-02 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0004_auto_20200302_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiledevice',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.MobileOwner'),
        ),
    ]
