# Generated by Django 2.2.1 on 2020-03-02 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0005_auto_20200302_0022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MobileDeviceOwner',
        ),
    ]
